spring:
  r2dbc:
    url: r2dbc:h2:mem:///dev
    # OR
    # url: r2dbc:h2:file:///~/webflux
    username: username
    password: password

  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG